import express from 'express';
import cors from 'cors';
const app=express();app.use(cors());app.use(express.json({limit:'15mb'}));
const PORT=process.env.PORT||8787,KEY=process.env.OPENROUTER_API_KEY,MODEL=process.env.OPENROUTER_MODEL||'openrouter/free';
if(!KEY)console.warn('OPENROUTER_API_KEY manquant.');
async function call(messages){if(!KEY)throw Error('OPENROUTER_API_KEY manquant sur le serveur.');const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${KEY}`,'Content-Type':'application/json','HTTP-Referer':'https://yprogress.local','X-Title':'YProgress'},body:JSON.stringify({model:MODEL,messages,temperature:.2})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||'OpenRouter error');return d?.choices?.[0]?.message?.content||''}
app.get('/health',(req,res)=>res.json({ok:true,model:MODEL}));
app.post('/analyze-meal',async(req,res)=>{try{const{imageBase64,mimeType='image/jpeg',context={}}=req.body;if(!imageBase64)return res.status(400).json({error:'imageBase64 manquant'});const prompt=`Tu es le nutritionniste IA de YProgress. Analyse la photo d'un repas. Estime les aliments et portions visibles. Sois prudent : une photo ne permet pas une précision parfaite. Retourne UNIQUEMENT un JSON valide, sans markdown, avec exactement ces clés: title (string), calories (number), protein (number), carbs (number), fat (number), confidence (number 0-1), notes (string). Les calories/macros sont des estimations. Objectif utilisateur: ${JSON.stringify(context)}.`;const out=await call([{role:'user',content:[{type:'text',text:prompt},{type:'image_url',image_url:{url:`data:${mimeType};base64,${imageBase64}`}}]}]);let parsed;try{parsed=JSON.parse(out.replace(/^```json\s*/,'').replace(/\s*```$/,''))}catch{parsed={title:'Analyse IA',text:out}}res.json(parsed)}catch(e){res.status(500).json({error:e.message})}});
app.post('/coach',async(req,res)=>{try{const{profile,today,phase}=req.body;const prompt=`Tu es le coach personnel YProgress. Donne un conseil court, concret et bienveillant. L'utilisateur veut prendre du muscle sans dopage. Ne prescris pas de régime extrême. Données: ${JSON.stringify({profile,today,phase})}. Réponds en français, 3 à 6 phrases maximum, avec une action immédiate si nécessaire.`;res.json({coach:await call([{role:'user',content:prompt}])})}catch(e){res.status(500).json({error:e.message})}});
app.listen(PORT,()=>console.log(`YProgress AI server: http://0.0.0.0:${PORT} • model=${MODEL}`));
