const assert=require("assert");
function test(name,fn){try{fn();console.log("PASS",name);return true}catch(e){console.error("FAIL",name,"-",e.message);return false}}
const results=[];
const flags=require("../../src/core/featureFlags.js");
results.push(test("native integrations gated",()=>{for(const k of ["healthKit","aiVision","aiCoach","voice","widget","liveActivity"])assert.equal(flags.FEATURES[k],false)}));
const sleep=require("../../src/services/health/sleepAutoDetection.js").sleepAutoDetection;
results.push(test("HealthKit sleep is confirmed",()=>{const r=sleep.inferWindow({lastActivityAt:"23:30",plannedWake:"07:30",healthKitSleep:{start:"23:40",end:"07:20"}});assert.equal(r.status,"confirmed");assert.equal(r.confidence,1)}));
results.push(test("device inactivity is only estimated",()=>{const r=sleep.inferWindow({lastActivityAt:"23:30",plannedWake:"07:30"});assert.equal(r.status,"estimated");assert(r.confidence<1)}));
results.push(test("no sleep signal is unknown",()=>{assert.equal(sleep.inferWindow({plannedWake:"07:30"}).status,"unknown")}));
results.push(test("morning reconciliation prefers HealthKit",()=>{const r=sleep.morningReconcile({estimated:{start:"23:30"},healthKitSleep:{start:"23:42",end:"07:30"}});assert.equal(r.status,"confirmed")}));
const auto=require("../../src/core/autopilot.js");
results.push(test("Autopilot caps actions at 3",()=>{const r=auto.buildAutopilotSnapshot({targets:{calories:2500,protein:110,steps:10000},total:{calories:900,protein:30},health:{sleepMin:350,steps:1000},phase:"test",training:{jjb:true}});assert(r.actions.length<=3)}));
results.push(test("minimum day contains no punitive action",()=>{const s=auto.minimumDay().join("|").toLowerCase();assert(!/fast|compens|punish/.test(s))}));
results.push(test("plateau requires sufficient history",()=>{const r=auto.detectPlateau([{weight:55},{weight:55}],"lean_gain");assert.equal(r.detected,false);assert.equal(r.reason,"insufficient_data")}));
results.push(test("healthy gain is not plateau",()=>{const h=Array.from({length:14},(_,i)=>({weight:55+i*.04}));assert.equal(auto.detectPlateau(h,"lean_gain").detected,false)}));
results.push(test("flat weight detects plateau and suggests 150 kcal",()=>{const h=Array.from({length:14},()=>({weight:55}));const r=auto.detectPlateau(h,"lean_gain");assert.equal(r.detected,true);assert.equal(r.suggestedCalories,150)}));
results.push(test("recovery score stays 0..100",()=>{for(const x of [{sleepMin:100},{sleepMin:450},{sleepMin:1000}]){const r=auto.calculateRecovery(x);assert(r>=0&&r<=100)}}));
const intel=require("../../src/core/intelligence.js");
results.push(test("sleep debt raises target",()=>{const r=intel.buildSleepRecommendation({nowMinutes:22*60,wakeMinutes:7*60+30,avgSleepMin:450,sleepDebtMin:120});assert(r.desiredSleepMin>450)}));
results.push(test("short remaining window becomes urgent",()=>{const r=intel.buildSleepRecommendation({nowMinutes:1*60,wakeMinutes:7*60,avgSleepMin:480,sleepDebtMin:60});assert.equal(r.urgency,"high")}));
const progression=require("../../src/core/progression.js");
const program=require("../../src/features/training/program.js");
const bench=program.WORKOUTS.Push.exercises[0];
const session=(reps=[10,10,10,10],load=60)=>({exerciseId:bench.id,week:1,actualLoad:load,sets:reps.map(r=>({load,reps:r,rir:2}))});
results.push(test("rest days never generate a load",()=>{for(const key of ["thu","sun"]){const day=program.dayByKey(key);assert.equal(program.WORKOUTS[day.name].type,"REST");assert.equal(progression.recommendNextLoad({exercise:{type:"REST"}}).recommendedLoad,null)}}));
results.push(test("week 1 uses starting load",()=>{const r=progression.recommendNextLoad({exercise:bench,history:[]});assert.equal(r.action,"start");assert.equal(r.recommendedLoad,60)}));
results.push(test("week 1 performance increases week 2 load",()=>{const r=progression.recommendNextLoad({exercise:bench,history:[session()],context:{sleepMin:480,fatigue:1,proteinRatio:1,calorieRatio:1,hydrationRatio:1}});assert.equal(r.action,"increase");assert.equal(r.recommendedLoad,62.5)}));
results.push(test("medium recovery holds load",()=>{const r=progression.recommendNextLoad({exercise:bench,history:[session()],context:{sleepMin:360,fatigue:4,proteinRatio:.7,calorieRatio:.9,hydrationRatio:.8,jjbSessions:1}});assert.equal(r.action,"hold");assert.equal(r.recommendedLoad,60)}));
results.push(test("poor recovery prudently decreases load",()=>{const r=progression.recommendNextLoad({exercise:bench,history:[session([7,6,5,5])],context:{sleepMin:300,fatigue:5,proteinRatio:.5,calorieRatio:.6,hydrationRatio:.4,jjbSessions:2}});assert.equal(r.action,"decrease");assert.equal(r.recommendedLoad,57.5)}));
results.push(test("exercise histories stay isolated",()=>{const h=[session(),{...session(),exerciseId:"squat"}];assert.equal(progression.historyForExercise(h,bench.id).length,1)}));
results.push(test("incomplete history cannot progress",()=>{const incomplete={...session(),sets:session().sets.slice(0,2)};assert.equal(progression.recommendNextLoad({exercise:bench,history:[incomplete]}).action,"hold")}));
results.push(test("recommended loads are never negative",()=>{const tiny={...bench,startLoad:1};const r=progression.recommendNextLoad({exercise:tiny,history:[{...session([1,1,1,1],1),exerciseId:tiny.id}],context:{sleepMin:100,fatigue:5}});assert(r.recommendedLoad>=0)}));
results.push(test("all seven days are selectable",()=>{assert.deepEqual(program.WEEK_DAYS.map(x=>x.label),["LUN","MAR","MER","JEU","VEN","SAM","DIM"])}));
results.push(test("friday saturday sunday programs exist",()=>{for(const key of ["fri","sat","sun"]){const day=program.dayByKey(key);assert(program.WORKOUTS[day.name])}}));
results.push(test("changing day does not mutate training data",()=>{const data=[session()];program.dayByKey("fri");program.dayByKey("sun");assert.equal(data.length,1);assert.equal(data[0].exerciseId,bench.id)}));
results.push(test("every strength exercise has a specific YouTube video",()=>{const ids=[];for(const workout of Object.values(program.WORKOUTS).filter(x=>x.type==="STRENGTH")){for(const exercise of workout.exercises){assert.equal(exercise.video.provider,"youtube");assert.equal(exercise.video.exerciseId,exercise.id);assert(exercise.video.id);ids.push(exercise.video.id)}}assert.equal(new Set(ids).size,ids.length)}));
results.push(test("JJB drill changes every session",()=>{const drills=[];for(let week=1;week<=4;week++){drills.push(program.jjbDrillFor(week,"tue").video.id+":"+program.jjbDrillFor(week,"tue").video.start);drills.push(program.jjbDrillFor(week,"sat").video.id+":"+program.jjbDrillFor(week,"sat").video.start)}assert.equal(new Set(drills).size,8)}));
results.push(test("JJB drills always include verified video metadata",()=>{for(const drill of program.JJB_DRILLS){assert.equal(drill.video.provider,"youtube");assert(drill.video.id);assert(drill.video.title);assert(drill.video.channel)}}));
results.push(test("exercise alternatives have separate identities and videos",()=>{for(const exercise of program.EXERCISE_ALTERNATIVES){assert(exercise.id);assert.equal(exercise.video.exerciseId,exercise.id);assert(exercise.video.id)}}));
results.push(test("custom exercise accepts personal starting load",()=>{const exercise=program.customExercise({name:"Mon curl préféré",startLoad:17.5});assert.equal(exercise.startLoad,17.5);assert(exercise.id.startsWith("custom-"))}));
const groceries=require("../../src/core/groceryPlanner.js");
results.push(test("grocery planner respects budget",()=>{for(const budget of [20,40,60,100]){const list=groceries.buildGroceryList({budget});assert(list.total<=budget);assert(list.items.length>0)}}));
results.push(test("grocery planner returns quantities and estimated totals",()=>{const list=groceries.buildGroceryList({budget:60,weeklyCalories:17500,weeklyProtein:770});assert(list.items.every(item=>item.quantity>0&&item.totalPrice>0));assert(list.estimatedCalories>0);assert(list.estimatedProtein>0)}));
const coach=require("../../server/coach.js");
results.push(test("coach payload is bounded",()=>{assert.throws(()=>coach.validatePayload({today:{text:"x".repeat(51000)}}),/PAYLOAD_TOO_LARGE/)}));
results.push(test("coach keeps only recent workout context",()=>{const p=coach.validatePayload({recentWorkouts:Array.from({length:50},(_,i)=>({i}))});assert.equal(p.recentWorkouts.length,30);assert.equal(p.recentWorkouts[0].i,20)}));
process.exit(results.every(Boolean)?0:1);
