const express = require('express');
const cors = require('cors');
const { coachHandler } = require('./coach');
const app = express();
app.use(cors());
app.use(express.json({ limit: '1mb' }));
app.get('/health', (req, res) => res.json({ ok: true, version: '15.0-ai-coach', model: process.env.OPENROUTER_MODEL || 'openrouter/free' }));
app.post('/coach', coachHandler);
app.post('/meal-analysis', (req, res) => res.status(501).json({ error: 'MEAL_ANALYSIS_NOT_IMPLEMENTED' }));
app.post('/weekly-insights', (req, res) => res.status(501).json({ error: 'WEEKLY_NOT_IMPLEMENTED' }));
app.post('/projection', (req, res) => res.status(501).json({ error: 'PROJECTION_NOT_IMPLEMENTED' }));
app.post('/restaurant', (req, res) => res.status(501).json({ error: 'RESTAURANT_NOT_IMPLEMENTED' }));
const port = process.env.PORT || 8787;
app.listen(port, () => console.log(`YProgress AI server on :${port} • model=${process.env.OPENROUTER_MODEL || 'openrouter/free'}`));
